### ISSUE TITLE
Unable to run StackBlitz examples in Firefox

### ISSUE THREAD

**Issue by Mathieu-COSYNS** [TanStack/tanstack.com#296]
I am running Firefox `131.0.3` on my Windows 11 computer. When I go to a example page, I cannot run the example.

For example when I go to <https://tanstack.com/query/latest/docs/framework/react/examples/simple>, I see this page:

![Image](https://github.com/user-attachments/assets/8c753b7b-3f33-4e97-899b-229a73ed3f63)

As you can see in the image above the preview window says "Unable to run Embedded Project". According to StackBlitz documentation <https://developer.stackblitz.com/platform/webcontainers/browser-support#embedding> embedding are only supported in Chromium-based browsers.

**Best solution**: Use another service that support Firefox.

If not possible I can still click on the link above :
![Image](https://github.com/user-attachments/assets/e26f3ab2-b725-429e-90db-6f72bad73857)
(<https://stackblitz.com/github/tanstack/query/tree/main/examples/react/simple?embed=1&theme=dark&preset=node&file=src/index.tsx>) but because in the url query parameters `embed=1` in a new tab I see this message:

![Image](https://github.com/user-attachments/assets/9d9b3062-e7f4-4134-96cb-754853b83bca)

If i manually remove `embed=1` (=> <https://stackblitz.com/github/tanstack/query/tree/main/examples/react/simple?theme=dark&preset=node&file=src/index.tsx>) then the stackblitz environment load properly.

**Alternative solution**: remove `embed=1` from the link near the title and only add `embed=1` for the iframe below.

**Comment by tannerlinsley** [comment]
Should be fixed now.

**Comment by Mathieu-COSYNS** [comment]
Hi @tannerlinsley,

Thanks for all the work you put into TanStack and the broader ecosystem.

Could you share a bit more detail on why this issue was marked as resolved? I’m still experiencing the same problem in Firefox 150.0.1, so I’d like to better understand whether there was a specific fix or workaround I may have missed (not deployed yet ?).

Thanks again

**Comment by Gallevy** [comment]
I also have the same issue @tannerlinsley , no example able to run. Standard chrome v150

**Comment by rorunsolu** [comment]
Im still getting the same problem right now despite the resolved status
